# Generated by Django 5.0.7 on 2024-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_users_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(default="Empty bio..."),
        ),
        migrations.AddField(
            model_name="user",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="users"),
        ),
    ]
