# Generated by Django 5.0.7 on 2024-07-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="pic",
            field=models.ImageField(default="users/no_picture.jpg", upload_to="users/"),
        ),
    ]
