# Generated by Django 5.0.7 on 2024-07-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cooking_time",
                    models.IntegerField(
                        default=0, help_text="Enter the cooking time in minutes"
                    ),
                ),
                (
                    "ingredients",
                    models.CharField(
                        help_text="Enter each ingredient separated by a comma",
                        max_length=250,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "easy"),
                            ("Medium", "medium"),
                            ("Intermediate", "intermediate"),
                            ("Hard", "hard"),
                        ],
                        default="Easy",
                        max_length=120,
                    ),
                ),
            ],
        ),
    ]
