# Generated by Django 5.0.7 on 2024-07-29 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_recipe_author_recipe_instructions_recipe_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
